### ISSUE TITLE
提交投票后报错

### ISSUE THREAD

**Issue by Maxxiecook** [hanxi/voting#1]
Warning: file_get_contents(http://www.123cha.com/ip/?q=222.186.10.113): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in D:\phpstudy_pro\WWW\WWW1\api\func.php on line 68
phpstudy  apache2.4 mysql5.7 php52-54  故障问题   fun.php 请问如何处理？

**Comment by hanxi** [comment]
应该是那个查ip地址的服务不能访问了，建议你找找别的项目，这个项目不维护了的。
